package com.example.auxanochatsdk.network

enum class SocketEvent(val event: String) {
    JOIN("join-group"),
    GET_CHAT("get-chat"),
   // GET_GROUPS("get-groups"),
    GET_GROUPS("get-group-list"),
    GET_GROUP("get-group"),
    GET_GROUP_RES("get-group-res"),
    SEND_MESSAGE("send-message"),
    RECEIVE_MESSAGE("receive-message"),
    TYPING_RES("typing-res"),
    GET_PREVIOUS_CHAT("get-chat-res"),
    //GET_PREVIOUS_CHAT("get-previous-chat"),
  //  GROUP_LIST("group-list"),
    GROUP_LIST("get-group-list-res"),
    LEAVE_GROUP("leave-group"),
    //LEAVE_GROUP("leave"),
    GET_PROFILE("get-profile"),
    PROFILE_RES("profile-res"),
    UPDATE_PROFILE("update-profile"),
    UPDATE_PROFILE_RES("update-profile-res"),
    EXIT_GROUP("exit-group"),
    EXIT_GROUP_RES("exit-group-res"),
    DELETE_CHAT_RES("delete-chat-res"),
    DELETE_CHAT("delete-chat"),
    USER_LIST("user-list"),
    USER_LIST_RES("user-list-res"),
    USER_DETAIL("user-detail"),
    USER_DETAIL_RES("user-detail_res"),
    CREATE_GROUP("create-group"),
    TYPING("typing"),
    ONLINE_STATUS("online"),
    ONLINE_STATUS_RES("online-status"),
    CREATE_GROUP_RES("create-group-res"),
    UNREAD_COUNT("unread-count"),
    UNREAD_COUNT_RES("unread-count-res"),
    ADD_MEMBER("add-member"),
    ADD_MEMBER_RES("add-member-res"),
    REMOVE_MEMBER("remove-member"),
    REMOVE_MEMBER_RES("remove-member-res"),
    DELETE_GROUP("delete-group"),
    DELETE_GROUP_RES("delete-group-res"),
    UPDATE_GROUP("update-group"),
    UPDATE_GROUP_RES("update-group-res"),
    CLEAR_CHAT("clear-chat"),
    CLEAR_CHAT_RES("clear-chat-res"),
    USER_ROLE("user-role"),
    USER_ROLE_RES("user-role-res"),
    GET_GROUPS_CALL("get-groups-call"),
    USER_UNREAD_COUNT("user-unread-count"),
    USER_UNREAD_COUNT_RES("user-unread-count-res"),
    FORWARD_FILE("forward-file")
}