package com.example.auxanochatsdk.network

object SocketFields {

    const val GROUP_ID = "groupId"
   // const val ID = "_id"
    const val ID = "userId"
    const val ID_ = "id"
    const val SECRET_KEY = "secretKey"
    const val MSG = "msg"
    const val IMAGE = "image"
    const val RID = "rid"
    const val TYPE = "type"
    const val NAME = "name"
    const val SENTBY = "sentBy"
    const val USER_ID = "userId"
    const val PROFILE_PICTURE = "profilePicture"
    const val CONTENT_TYPE = "contentType"
    const val FILE_NAME = "fileName"
    const val UPDATE_PROFILE_RES = "update-profile-res"
    const val SERVER_USER_ID = "serverUserId"
    const val MOBILE_EMAIL = "mobile_email"
    const val GROUPS = "groups"
    const val IS_GROUP = "isGroup"
    const val CREATE_BY = "createdBy"
    const val GROUP_IMAGE = "groupImage"
    const val MEMBERS = "members"
    const val GROUP_PERMISSION = "groupPermission"
    const val IS_DEACTIVATE_USER = "isDeactivateUser"
    const val MODIFIED_BY = "modifiedBy"
    const val ONLINE = "online"
    const val PINNED_GROUP = "pinnedGroup"
    const val READ_COUNT = "readCount"
    const val TYPING = "typing"
    const val BLOCK_USER = "blockUsers"
    const val VIEW_BY = "viewBy"
    const val RECENT_MESSAGE = "recentMessage"
    const val PIN_GROUP_FOR_ALL = "pinGroupForAll"
    const val USERS = "users"
    const val UN_READ_COUNT = "unreadCount"
    const val GROUP_DETAILS = "groupDetails"
    const val IS_READ = "isRead"
    const val IS_TYPING = "isTyping"
    const val READ_BY = "readBy"
    const val SENT_AT = "sentAt"
    const val TIME_MILLI_SECOND = "timeMilliSeconds"
    const val MESSAGE_OBJ = "messageObj"
    const val FILE = "file"
    const val GROUP_NAME = "groupName"
    const val REPLY_USER = "replyUser"
    const val REPLY_MSG = "replyMsg"
    const val REPLY_MSG_ID = "replyMsgId"
    const val REPLY_USER_ID = "replyUserId"
    const val REPLY_MSG_TYPE = "replyMsgType"
    const val FILE_ARR = "fileArr"
    const val GROUP_ARR = "groupArr"
    const val START_AT = "startAt"
    const val SENDER_NAME = "senderName"

}